import { Inter } from "next/font/google";
import "./globals.css";
import Auth from "@/companents/adminpanel/Auth"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <AuthProvider> */}
{/* <AuthProvider> */}
<Auth>
        {children}
</Auth>
{/* </AuthProvider> */}
        {/* </AuthProvider> */}
        
        </body>
    </html>
  );
}
